batch_size: 32
workers: 0
nepoch: 100
model_name: msn
load_model: log/msn_cd_debug_2021-08-10T17:55:45/network.pth
start_epoch: 0
num_points: 2048
work_dir: log/
flag: debug
loss: cd
manual_seed: null
use_mean_feature: False
step_interval_to_print: 500
epoch_interval_to_save: 1
epoch_interval_to_val: 10
varying_constant: null
varying_constant_epochs: null

lr: 0.001
lr_decay: True
lr_decay_interval: null
lr_decay_rate: null
lr_step_decay_epochs: 20,40
lr_step_decay_rates: 0.1,0.1
lr_clip: null
optimizer: Adam
weight_decay: 0
betas: 0.9, 0.999

n_primitives: 16

# test
save_vis: True